Sprint 5: implement profile & settings pages
ClevertecFrontendLab/SashaPt pull request #5
Opened 2024-03-25 07:09 UTC by SashaPt

2024-03-25 07:11 UTC, ValadzkoAliaksei commented
#  Результаты тестов
Процент пройденных тестов: 80%.
Общее количество тестов: 5.
Количество непройденных тестов: 1.

2024-03-25 07:41 UTC, ValadzkoAliaksei commented
#  Результаты тестов
Процент пройденных тестов: 80%.
Общее количество тестов: 5.
Количество непройденных тестов: 1.

2024-03-25 07:49 UTC, ValadzkoAliaksei commented
#  Результаты тестов
Процент пройденных тестов: 80%.
Общее количество тестов: 5.
Количество непройденных тестов: 1.

2024-03-25 07:57 UTC, ValadzkoAliaksei commented
#  Результаты тестов
Процент пройденных тестов: 80%.
Общее количество тестов: 5.
Количество непройденных тестов: 1.

2024-03-25 08:42 UTC, ValadzkoAliaksei commented
#  Результаты тестов
Процент пройденных тестов: 80%.
Общее количество тестов: 5.
Количество непройденных тестов: 1.

2024-03-25 09:02 UTC, ValadzkoAliaksei commented
#  Результаты тестов
Процент пройденных тестов: 80%.
Общее количество тестов: 5.
Количество непройденных тестов: 1.

2024-03-25 09:46 UTC, ValadzkoAliaksei commented
#  Результаты тестов
Процент пройденных тестов: 80%.
Общее количество тестов: 5.
Количество непройденных тестов: 1.

2024-03-25 09:49 UTC, ValadzkoAliaksei commented
#  Результаты тестов
Процент пройденных тестов: 100%.
Общее количество тестов: 5.
Количество непройденных тестов: 0.
***
**buy-tariff-success_1440x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/SashaPt/1711360171/buy-tariff-success_1440x900.png)
***
**default-profile-page_1440x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/SashaPt/1711360171/default-profile-page_1440x900.png)
***
**default-settings-page_1440x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/SashaPt/1711360171/default-settings-page_1440x900.png)
***
**feedbacks with photo_1440x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/SashaPt/1711360171/feedbacks%20with%20photo_1440x900.png)
***
**modal-big-photo_1440x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/SashaPt/1711360171/modal-big-photo_1440x900.png)
***
**profile-modal-error_1440x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/SashaPt/1711360171/profile-modal-error_1440x900.png)
***
**profile-modal-success_1440x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/SashaPt/1711360171/profile-modal-success_1440x900.png)
***
**settings-page-with-sider_360x740.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/SashaPt/1711360171/settings-page-with-sider_360x740.png)
***
**settings-pro-cards_360x740.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/SashaPt/1711360171/settings-pro-cards_360x740.png)
***
**settings-sider-pro_833x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/SashaPt/1711360171/settings-sider-pro_833x900.png)

2024-03-25 13:38 UTC, kvadratikk requested changes

2024-03-25 13:38 UTC, kvadratikk commented on src/pages/profile-page/components/upload-image/upload-image.tsx
картинки почему-то двоятся 
![image](https://github.com/ClevertecFrontendLab/SashaPt/assets/78285127/70c7ae5d-b3b8-4295-b958-1438f3fd88d5)

2024-03-25 13:38 UTC, kvadratikk commented on src/pages/profile-page/components/upload-image/upload-image.tsx
> +
картинка не отображается, не видно алерта
![image](https://github.com/ClevertecFrontendLab/SashaPt/assets/78285127/6376d5e6-12c2-4f70-93cc-311ec373cbbf)
![image](https://github.com/ClevertecFrontendLab/SashaPt/assets/78285127/cf21ca94-e0b4-4454-b829-024f03d33edf)

2024-03-25 13:38 UTC, kvadratikk commented on src/pages/settings-page/components/settings-drawer/settings-drawer.tsx
иконка не та 
![image](https://github.com/ClevertecFrontendLab/SashaPt/assets/78285127/034364a8-f9c8-46c5-a57a-ed81bbe542d0)
![image](https://github.com/ClevertecFrontendLab/SashaPt/assets/78285127/7f6aa507-c5b1-49ab-a11f-5ad46ce3442d)

2024-03-25 19:32 UTC, byshlata requested changes
замечания по коду

2024-03-25 19:32 UTC, byshlata commented on src/components/header/pageHeader.scss
> +            font-size: 20px;
в переменные

2024-03-25 19:32 UTC, byshlata commented on src/components/header/pageHeader.scss
> +                margin-right: 10px;
в переменные

2024-03-25 19:32 UTC, byshlata commented on src/components/sider/pageSider.tsx
> +            console.log(error);
?

2024-03-25 19:32 UTC, byshlata commented on src/index.css
> +    opacity: 1 !important;
!impotant убираем

2024-03-25 19:32 UTC, byshlata commented on src/index.css
> +    border-color: #2f54eb;
в переменные

2024-03-25 19:32 UTC, byshlata commented on src/pages/error-page/error-page.scss
> +    border-radius: 8px;
в переменные

2024-03-25 19:32 UTC, byshlata commented on src/pages/profile-page/components/profile-error-modal/profile-error-modal.tsx
> +    isOpen: boolean;
вынеси в отдельный тип

2024-03-25 19:32 UTC, byshlata commented on src/pages/profile-page/components/profile-error-modal/profile-error-modal.tsx
> +    return (
return можно опустить

2024-03-25 19:32 UTC, byshlata commented on src/pages/profile-page/profile-page.scss
> +        padding: 16px 24px;
в переменные, как и остальные похожие значения

2024-03-25 19:32 UTC, byshlata commented on src/pages/profile-page/profile-page.tsx
> +                                                        format='DD.MM.YYYY'
в констаты

2024-03-25 19:32 UTC, byshlata commented on src/pages/settings-page/components/settings-drawer/settings-drawer.tsx
> +    const settingsOptionsData = [
вот это в компоненте не нужно, можно вынести выше

2024-03-25 19:32 UTC, byshlata commented on src/pages/settings-page/components/settings-drawer/settings-drawer.tsx
> +    onClose: () => void;
отдельный тип

2024-03-25 19:32 UTC, byshlata commented on src/pages/settings-page/components/settings-drawer/settings-drawer.tsx
> +                                    marginRight: '-7px',
в css

2024-03-25 19:32 UTC, byshlata commented on src/pages/settings-page/components/settings-drawer/settings-drawer.tsx
> +                    {moment(new Date(Date.parse(user.tariff.expired || ''))).format('DD.MM')}
это должна быть отдельная функуция. как это тестить?

2024-03-25 19:32 UTC, byshlata commented on src/pages/settings-page/components/settings-drawer/settings-drawer.tsx
> +                                    style={{ color: '#bfbfbf', fontSize: '18px' }}
в css

2024-03-25 19:32 UTC, byshlata commented on src/pages/settings-page/components/settings-items/settings-items.tsx
> +    return (
return ?

2024-03-25 19:32 UTC, byshlata commented on src/pages/settings-page/components/settings-tariffs-form/settings-tariffs-form.tsx
> +            console.log(error);
?

2024-03-25 19:32 UTC, byshlata commented on src/pages/settings-page/settings-page.tsx
> +                                                            Date.parse(user.tariff.expired || ''),
отдельно

2024-03-26 14:17 UTC, ValadzkoAliaksei commented
#  Результаты тестов
Процент пройденных тестов: 100%.
Общее количество тестов: 5.
Количество непройденных тестов: 0.
***
**buy-tariff-success_1440x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/SashaPt/1711462676/buy-tariff-success_1440x900.png)
***
**default-profile-page_1440x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/SashaPt/1711462676/default-profile-page_1440x900.png)
***
**default-settings-page_1440x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/SashaPt/1711462676/default-settings-page_1440x900.png)
***
**feedbacks with photo_1440x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/SashaPt/1711462676/feedbacks%20with%20photo_1440x900.png)
***
**modal-big-photo_1440x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/SashaPt/1711462676/modal-big-photo_1440x900.png)
***
**profile-modal-error_1440x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/SashaPt/1711462676/profile-modal-error_1440x900.png)
***
**profile-modal-success_1440x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/SashaPt/1711462676/profile-modal-success_1440x900.png)
***
**settings-page-with-sider_360x740.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/SashaPt/1711462676/settings-page-with-sider_360x740.png)
***
**settings-pro-cards_360x740.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/SashaPt/1711462676/settings-pro-cards_360x740.png)
***
**settings-sider-pro_833x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/SashaPt/1711462676/settings-sider-pro_833x900.png)

2024-03-28 09:17 UTC, byshlata approved these changes

2024-03-28 09:17 UTC, merged