Sprint 6: implement training page
ClevertecFrontendLab/SashaPt pull request #6
Opened 2024-04-10 07:29 UTC by SashaPt

2024-04-10 08:23 UTC, Ivan6813 requested changes

2024-04-10 08:23 UTC, Ivan6813 commented on src/pages/calendar-page/components/training-form-list/training-form-list.tsx
> +                              return {
тут можно убрать лишний return `exercises.map((exercise) => ( {...} )` завернув в круглые скодки

2024-04-10 08:23 UTC, Ivan6813 commented on src/pages/calendar-page/components/training-form-list/training-form-list.tsx
> +                                    onClick={() => add()}
` onClick={ add }` можно сократить

2024-04-10 08:23 UTC, Ivan6813 commented on src/pages/training-page/components/invitations/invitations.tsx
> +                            if (isItemsCollapsed) {
`if (isItemsCollapsed && index >= 1) {` можно обойтись одним if

2024-04-10 08:23 UTC, Ivan6813 commented on src/pages/training-page/components/partner-card/partner-card.tsx
> +                className={`partner-card ${isJoint ? 'partner-card-joint' : ''} ${
чтобы не городить такое можно посмотреть в сторону использования библиотеки classNames, как совет

2024-04-10 10:03 UTC, ValadzkoAliaksei commented
#  Результаты тестов
Процент пройденных тестов: 100%.
Общее количество тестов: 5.
Количество непройденных тестов: 0.
***
**come-to-trainings-1_1440x900 (1).png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/SashaPt/1712743390/come-to-trainings-1_1440x900%20(1).png)
***
**come-to-trainings-1_1440x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/SashaPt/1712743390/come-to-trainings-1_1440x900.png)
***
**create-joint-training-1_1440x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/SashaPt/1712743390/create-joint-training-1_1440x900.png)
***
**create-joint-training-2_1440x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/SashaPt/1712743390/create-joint-training-2_1440x900.png)
***
**create-joint-training-3_360x740.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/SashaPt/1712743390/create-joint-training-3_360x740.png)
***
**create-joint-training-4_360x740.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/SashaPt/1712743390/create-joint-training-4_360x740.png)
***
**create-new-training-1_833x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/SashaPt/1712743390/create-new-training-1_833x900.png)
***
**create-new-training-2_833x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/SashaPt/1712743390/create-new-training-2_833x900.png)
***
**take-joint-training-1_833x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/SashaPt/1712743390/take-joint-training-1_833x900.png)
***
**take-joint-training-2_833x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/SashaPt/1712743390/take-joint-training-2_833x900.png)
***
**take-joint-training-3_833x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/SashaPt/1712743390/take-joint-training-3_833x900.png)
***
**take-joint-training-4_833x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/SashaPt/1712743390/take-joint-training-4_833x900.png)
***
**update-trainings-1_360x740.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/SashaPt/1712743390/update-trainings-1_360x740.png)
***
**update-trainings-2_360x740.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/SashaPt/1712743390/update-trainings-2_360x740.png)
***
**update-trainings-3_360x740.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/SashaPt/1712743390/update-trainings-3_360x740.png)

2024-04-10 10:34 UTC, Ivan6813 approved these changes

2024-04-10 19:43 UTC, ValadzkoAliaksei requested changes

2024-04-10 19:43 UTC, ValadzkoAliaksei commented on src/pages/calendar-page/components/calendar-cell/calendar-cell.tsx
> +            } ${currentTrainings.length ? 'calendar-cell-full' : 'calendar-cell-empty'} ${small && date.isSameOrBefore(moment())  ? 'calendar-cell-previous' : ''}`}
попробуй библиотечку 
https://www.npmjs.com/package/classnames

2024-04-10 19:47 UTC, ValadzkoAliaksei requested changes

2024-04-10 19:47 UTC, ValadzkoAliaksei commented on src/components/header/pageHeader.scss
> +                margin-right: var(--spacing-xs);
![image](https://github.com/ClevertecFrontendLab/SashaPt/assets/61273546/342c84f9-e5a6-4477-9847-4fa3e9f8605b)
после модалки ошибки ничего не кликается(
может маска осталась...

2024-04-11 07:12 UTC, ValadzkoAliaksei commented
#  Результаты тестов
Процент пройденных тестов: 100%.
Общее количество тестов: 5.
Количество непройденных тестов: 0.
***
**come-to-trainings-1_1440x900 (1).png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/SashaPt/1712819561/come-to-trainings-1_1440x900%20(1).png)
***
**come-to-trainings-1_1440x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/SashaPt/1712819561/come-to-trainings-1_1440x900.png)
***
**create-joint-training-1_1440x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/SashaPt/1712819561/create-joint-training-1_1440x900.png)
***
**create-joint-training-2_1440x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/SashaPt/1712819561/create-joint-training-2_1440x900.png)
***
**create-joint-training-3_360x740.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/SashaPt/1712819561/create-joint-training-3_360x740.png)
***
**create-joint-training-4_360x740.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/SashaPt/1712819561/create-joint-training-4_360x740.png)
***
**create-new-training-1_833x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/SashaPt/1712819561/create-new-training-1_833x900.png)
***
**create-new-training-2_833x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/SashaPt/1712819561/create-new-training-2_833x900.png)
***
**take-joint-training-1_833x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/SashaPt/1712819561/take-joint-training-1_833x900.png)
***
**take-joint-training-2_833x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/SashaPt/1712819561/take-joint-training-2_833x900.png)
***
**take-joint-training-3_833x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/SashaPt/1712819561/take-joint-training-3_833x900.png)
***
**take-joint-training-4_833x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/SashaPt/1712819561/take-joint-training-4_833x900.png)
***
**update-trainings-1_360x740.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/SashaPt/1712819561/update-trainings-1_360x740.png)
***
**update-trainings-2_360x740.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/SashaPt/1712819561/update-trainings-2_360x740.png)
***
**update-trainings-3_360x740.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/SashaPt/1712819561/update-trainings-3_360x740.png)

2024-04-11 07:13 UTC, SashaPt commented on src/components/header/pageHeader.scss
> +                margin-right: var(--spacing-xs);
https://github.com/ClevertecFrontendLab/SashaPt/assets/98906181/4e507278-db8c-493a-aebe-2acbd31e49a0

Не отлавливается такое поведение на странице Календарь, в тренировках исправила

2024-04-11 09:35 UTC, ValadzkoAliaksei approved these changes

2024-04-11 09:42 UTC, merged